from __future__ import annotations

import sys
import threading
import time
from pathlib import Path

import pytest

from alogs.sources import adb_source
from alogs.sources.adb_source import (
    AdbError,
    AdbSource,
    Device,
    choose_device,
    find_adb,
    list_devices,
    process_list,
)

FAKE_ADB = Path(__file__).parent / "fake_adb.py"
LINES = [
    "01-02 03:04:05.678  1234  5678 D MyTag   : hello",
    "01-02 03:04:05.679  1234  5678 I MyTag   : world",
]


@pytest.fixture
def fake_adb(tmp_path, monkeypatch):
    log = tmp_path / "device.log"
    log.write_text("\n".join(LINES) + "\n", encoding="utf-8")
    calls = tmp_path / "calls.txt"
    monkeypatch.setenv("ALOGS_ADB", f'"{sys.executable}" "{FAKE_ADB}"')
    monkeypatch.setenv("FAKE_ADB_LOG", str(log))
    monkeypatch.setenv("FAKE_ADB_CALLS", str(calls))
    for var in ("FAKE_ADB_HANG", "FAKE_ADB_NO_MODIFIERS", "FAKE_ADB_DELAY", "FAKE_ADB_EXIT", "FAKE_ADB_DEVICES"):
        monkeypatch.delenv(var, raising=False)
    return calls


def test_find_adb_env_override(monkeypatch):
    monkeypatch.setenv("ALOGS_ADB", r'"C:\Program Files\py.exe" "C:\x\fake adb.py"')
    assert find_adb() == [r"C:\Program Files\py.exe", r"C:\x\fake adb.py"]


def test_find_adb_sdk_fallback(tmp_path, monkeypatch):
    monkeypatch.delenv("ALOGS_ADB", raising=False)
    monkeypatch.chdir(tmp_path)  # no local.properties around
    monkeypatch.setattr(adb_source.shutil, "which", lambda name: None)
    exe = "adb.exe" if sys.platform == "win32" else "adb"
    tools = tmp_path / "sdk" / "platform-tools"
    tools.mkdir(parents=True)
    (tools / exe).write_text("")
    monkeypatch.setenv("ANDROID_HOME", str(tmp_path / "sdk"))
    assert find_adb() == [str(tools / exe)]
    monkeypatch.delenv("ANDROID_HOME")
    monkeypatch.setattr(adb_source, "_sdk_dirs", lambda: [])
    assert find_adb() is None


def test_list_devices(fake_adb, monkeypatch):
    monkeypatch.setenv("FAKE_ADB_DEVICES", "emulator-5554:device,R58M:unauthorized")
    assert list_devices(find_adb()) == [Device("emulator-5554", "device"), Device("R58M", "unauthorized")]


def test_choose_device():
    ok, bad, off = Device("a", "device"), Device("b", "unauthorized"), Device("c", "offline")
    assert choose_device([ok], None) is ok
    assert choose_device([ok, bad], "a") is ok
    with pytest.raises(AdbError, match="no devices"):
        choose_device([], None)
    with pytest.raises(AdbError, match="more than one device: a, b"):
        choose_device([ok, bad], None)
    with pytest.raises(AdbError, match="unauthorized"):
        choose_device([bad], None)
    with pytest.raises(AdbError, match="offline"):
        choose_device([off], None)
    with pytest.raises(AdbError, match="'zzz' not found"):
        choose_device([ok], "zzz")


def test_stream_uses_preferred_format(fake_adb):
    src = AdbSource(find_adb(), "emulator-5554")
    lines = [line for line in src.iter_lines() if line is not None]
    assert lines == LINES
    assert src.returncode == 0
    assert "device went away" in src.error
    assert fake_adb.read_text().splitlines() == [
        "-s emulator-5554 logcat -v threadtime -v year -v usec",
    ]


def test_stream_falls_back_to_plain_threadtime(fake_adb, monkeypatch):
    monkeypatch.setenv("FAKE_ADB_NO_MODIFIERS", "1")
    src = AdbSource(find_adb(), "emulator-5554")
    lines = [line for line in src.iter_lines() if line is not None]
    assert lines == LINES
    assert fake_adb.read_text().splitlines() == [
        "-s emulator-5554 logcat -v threadtime -v year -v usec",
        "-s emulator-5554 logcat -v threadtime",
    ]


def test_idle_yields_none_and_stop_ends_stream(fake_adb, monkeypatch):
    monkeypatch.setenv("FAKE_ADB_HANG", "1")
    src = AdbSource(find_adb(), "emulator-5554")
    seen: list[str | None] = []
    done = threading.Event()

    def consume():
        for line in src.iter_lines():
            seen.append(line)
        done.set()

    threading.Thread(target=consume, daemon=True).start()
    deadline = time.monotonic() + 10
    while seen.count(None) < 2 and time.monotonic() < deadline:
        time.sleep(0.05)
    assert [s for s in seen if s is not None] == LINES
    assert None in seen
    src.stop()
    assert done.wait(10), "stream did not end after stop()"


def test_process_list(fake_adb, tmp_path, monkeypatch):
    ps = tmp_path / "ps.txt"
    ps.write_text("PID NAME\n 4321 com.example.app\n", encoding="utf-8")
    monkeypatch.setenv("FAKE_ADB_PS", str(ps))
    assert "com.example.app" in process_list(find_adb(), "emulator-5554")


def test_local_properties_windows_escaping(tmp_path):
    from alogs.sources.adb_source import sdk_dir_from_local_properties

    (tmp_path / "local.properties").write_text(
        "## This file is automatically generated by Android Studio.\n"
        "# Do not modify this file -- YOUR CHANGES WILL BE ERASED!\n"
        r"sdk.dir=C\:\\Users\\me\\AppData\\Local\\Android\\Sdk" "\n",
        encoding="utf-8",
    )
    assert sdk_dir_from_local_properties(tmp_path) == Path(r"C:\Users\me\AppData\Local\Android\Sdk")


def test_local_properties_forms_and_parent_lookup(tmp_path):
    from alogs.sources.adb_source import sdk_dir_from_local_properties

    project = tmp_path / "project"
    sub = project / "app" / "src"
    sub.mkdir(parents=True)
    (project / "local.properties").write_text("! comment\n" r"sdk.dir : /opt/android\u002dsdk" "\n", encoding="utf-8")
    assert sdk_dir_from_local_properties(sub) == Path("/opt/android-sdk")
    # the nearest local.properties decides, even if it has no sdk.dir
    (sub / "local.properties").write_text("ndk.dir=/x\n", encoding="utf-8")
    assert sdk_dir_from_local_properties(sub) is None


def test_find_adb_order(tmp_path, monkeypatch):
    monkeypatch.delenv("ALOGS_ADB", raising=False)
    exe = "adb.exe" if sys.platform == "win32" else "adb"

    def sdk(name):
        tools = tmp_path / name / "platform-tools"
        tools.mkdir(parents=True)
        (tools / exe).write_text("")
        return tmp_path / name, str(tools / exe)

    props_sdk, props_adb = sdk("props-sdk")
    home_sdk, home_adb = sdk("home-sdk")
    project = tmp_path / "project"
    project.mkdir()
    escaped = str(props_sdk).replace("\\", "\\\\").replace(":", "\\:")  # as Android Studio writes it
    (project / "local.properties").write_text(f"sdk.dir={escaped}\n", encoding="utf-8")
    monkeypatch.chdir(project)
    monkeypatch.setenv("ANDROID_HOME", str(home_sdk))

    monkeypatch.setattr(adb_source.shutil, "which", lambda name: "/on/path/adb")
    assert find_adb() == ["/on/path/adb"]  # 1. PATH
    monkeypatch.setattr(adb_source.shutil, "which", lambda name: None)
    assert find_adb() == [props_adb]  # 2. local.properties
    (project / "local.properties").unlink()
    assert find_adb() == [home_adb]  # 3. ANDROID_HOME
